### ISSUE TITLE
STS header is sent twice with different values

### ISSUE THREAD

**Issue by Bisaloo** [despora/diaspora#12]
https://securityheaders.com/?q=despora.de&followRedirects=on

https://hstspreload.org/?domain=despora.de

The STS header is sent twice with different values, which confuses browsers that try to add it to their preload list.

The server config file should probably be updated to only send 

    Strict-Transport-Security    max-age=31536000; includeSubDomains; preload

**Comment by prellele** [comment]
Thank you, it has been fixed now
